# Generated by Django 5.2.8 on 2025-11-19 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único do módulo', max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador único do módulo (usado em URLs)', max_length=100, unique=True, verbose_name='Slug')),
                ('module_type', models.CharField(choices=[('ecommerce', 'E-commerce'), ('messages', 'Mensagens'), ('blog', 'Blog'), ('analytics', 'Analytics'), ('custom', 'Personalizado')], default='custom', max_length=50, verbose_name='Tipo de Módulo')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do módulo', verbose_name='Descrição')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão')),
                ('is_active', models.BooleanField(default=False, help_text='Define se o módulo está ativo no sistema', verbose_name='Ativo')),
                ('is_core', models.BooleanField(default=False, help_text='Módulos core não podem ser desativados', verbose_name='Módulo Core')),
                ('app_name', models.CharField(help_text='Nome do app Django correspondente (ex: ecommerce, messages)', max_length=100, verbose_name='Nome do App Django')),
                ('icon', models.CharField(blank=True, help_text='Classe CSS do ícone (ex: fa fa-shopping-cart)', max_length=50, verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no menu', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Pode Visualizar')),
                ('can_create', models.BooleanField(default=False, verbose_name='Pode Criar')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Pode Editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Pode Deletar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='modules.module', verbose_name='Módulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Módulo',
                'verbose_name_plural': 'Permissões de Módulos',
                'ordering': ['module', 'user'],
                'unique_together': {('module', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Nome da configuração', max_length=100, verbose_name='Chave')),
                ('value', models.TextField(help_text='Valor da configuração (pode ser JSON)', verbose_name='Valor')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo de Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='modules.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Configuração de Módulo',
                'verbose_name_plural': 'Configurações de Módulos',
                'ordering': ['module', 'key'],
                'unique_together': {('module', 'key')},
            },
        ),
    ]
