# Generated by Django 5.2.8 on 2025-11-19 11:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Descrição Curta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço original (para exibir desconto)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Comparativo')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Custo')),
                ('sku', models.CharField(help_text='Código único do produto', max_length=100, unique=True, verbose_name='SKU')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('stock_status', models.CharField(choices=[('in_stock', 'Em Estoque'), ('out_of_stock', 'Sem Estoque'), ('pre_order', 'Pré-venda')], default='in_stock', max_length=20, verbose_name='Status de Estoque')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/products/%Y/%m/', verbose_name='Imagem Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Para carrinho de usuários não autenticados', max_length=100, verbose_name='Chave da Sessão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status do Pagamento')),
                ('shipping_name', models.CharField(max_length=200, verbose_name='Nome para Entrega')),
                ('shipping_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('shipping_address', models.CharField(max_length=300, verbose_name='Endereço')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('shipping_state', models.CharField(max_length=100, verbose_name='Estado')),
                ('shipping_zipcode', models.CharField(max_length=20, verbose_name='CEP')),
                ('shipping_country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo de Envio')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Imposto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Armazena o nome do produto no momento da compra', max_length=200, verbose_name='Nome do Produto')),
                ('product_sku', models.CharField(max_length=100, verbose_name='SKU do Produto')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecommerce/categories/%Y/%m/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.productcategory', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.productcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ecommerce/products/%Y/%m/', verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem de Produto',
                'verbose_name_plural': 'Imagens de Produtos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço no momento da adição ao carrinho', max_digits=10, verbose_name='Preço Unitário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.cart', verbose_name='Carrinho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Carrinho',
                'verbose_name_plural': 'Itens do Carrinho',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
