# Generated by Django 5.2.8 on 2025-11-18 21:43

import ckeditor_uploader.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Meu Blog', max_length=100, verbose_name='Nome do Site')),
                ('site_description', models.TextField(blank=True, verbose_name='Descrição do Site')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo do Site')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texto do Rodapé')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords Global')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Comentários Habilitados')),
                ('comments_require_approval', models.BooleanField(default=True, verbose_name='Comentários Requerem Aprovação')),
                ('posts_per_page', models.IntegerField(default=10, verbose_name='Posts por Página')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='Arquivo')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamanho')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('caption', models.TextField(blank=True, verbose_name='Legenda')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Imagem Destacada')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Mostrar no Menu')),
                ('menu_order', models.IntegerField(default=0, verbose_name='Ordem no Menu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Descrição')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Resumo')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d/', verbose_name='Imagem Destacada')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('scheduled', 'Agendado')], default='draft', max_length=10, verbose_name='Status')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Permitir Comentários')),
                ('views', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Descrição')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Meta Keywords')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Categoria')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Comentário')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='Responder a')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['created_at'],
            },
        ),
    ]
