# Generated by Django 5.2.8 on 2025-11-18 22:22

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Seção')),
                ('section_type', models.CharField(choices=[('hero', 'Hero/Banner'), ('text', 'Texto'), ('text_image', 'Texto com Imagem'), ('image_gallery', 'Galeria de Imagens'), ('cards', 'Cards/Destaques'), ('testimonials', 'Depoimentos'), ('cta', 'Call to Action'), ('features', 'Recursos/Features'), ('html', 'HTML Customizado')], default='text', max_length=20, verbose_name='Tipo de Seção')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Imagem')),
                ('image_position', models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita')], default='right', max_length=10, verbose_name='Posição da Imagem')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Texto do Botão')),
                ('button_link', models.CharField(blank=True, max_length=300, verbose_name='Link do Botão')),
                ('background_color', models.CharField(choices=[('white', 'Branco'), ('light', 'Cinza Claro'), ('dark', 'Escuro'), ('primary', 'Cor Primária'), ('secondary', 'Cor Secundária')], default='white', max_length=20, verbose_name='Cor de Fundo')),
                ('custom_css_class', models.CharField(blank=True, max_length=100, verbose_name='Classe CSS Customizada')),
                ('custom_html', models.TextField(blank=True, verbose_name='HTML Customizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='blog.page', verbose_name='Página')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.section', verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Seção da Página',
                'verbose_name_plural': 'Seções da Página',
                'ordering': ['order'],
                'unique_together': {('page', 'section', 'order')},
            },
        ),
    ]
