# Generated by Django 5.2.8 on 2025-11-18 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_section_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_page',
            field=models.ForeignKey(blank=True, help_text='Selecione uma página para ser a home. Se vazio, mostra lista de posts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_home_page', to='blog.page', verbose_name='Página Inicial'),
        ),
    ]
