# Generated by Django 5.2.8 on 2025-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sitesettings_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tema')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('primary_color', models.CharField(default='#3498db', help_text='Formato: #RRGGBB', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=7, verbose_name='Cor Secundária')),
                ('accent_color', models.CharField(default='#e74c3c', max_length=7, verbose_name='Cor de Destaque')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='Cor do Texto')),
                ('heading_color', models.CharField(default='#2c3e50', max_length=7, verbose_name='Cor dos Títulos')),
                ('link_color', models.CharField(default='#3498db', max_length=7, verbose_name='Cor dos Links')),
                ('link_hover_color', models.CharField(default='#2980b9', max_length=7, verbose_name='Cor dos Links (Hover)')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor de Fundo')),
                ('secondary_bg_color', models.CharField(default='#f5f5f5', max_length=7, verbose_name='Cor de Fundo Secundária')),
                ('header_bg_color', models.CharField(default='#2c3e50', max_length=7, verbose_name='Cor de Fundo do Header')),
                ('header_text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do Texto do Header')),
                ('footer_bg_color', models.CharField(default='#34495e', max_length=7, verbose_name='Cor de Fundo do Footer')),
                ('footer_text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do Texto do Footer')),
                ('button_bg_color', models.CharField(default='#3498db', max_length=7, verbose_name='Cor de Fundo do Botão')),
                ('button_text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do Texto do Botão')),
                ('button_hover_bg_color', models.CharField(default='#2980b9', max_length=7, verbose_name='Cor do Botão (Hover)')),
                ('font_family', models.CharField(default="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif", max_length=200, verbose_name='Família de Fonte')),
                ('heading_font_family', models.CharField(blank=True, help_text='Se vazio, usa a mesma fonte do texto', max_length=200, verbose_name='Família de Fonte dos Títulos')),
                ('font_size_base', models.CharField(default='16px', max_length=10, verbose_name='Tamanho Base da Fonte')),
                ('line_height', models.CharField(default='1.6', max_length=10, verbose_name='Altura da Linha')),
                ('border_radius', models.CharField(default='8px', max_length=10, verbose_name='Raio das Bordas')),
                ('box_shadow', models.CharField(default='0 2px 5px rgba(0,0,0,0.1)', max_length=100, verbose_name='Sombra dos Boxes')),
                ('custom_css', models.TextField(blank=True, help_text='CSS adicional para personalizar o tema', verbose_name='CSS Customizado')),
                ('is_active', models.BooleanField(default=False, verbose_name='Tema Ativo')),
                ('is_default', models.BooleanField(default=False, help_text='Tema usado quando nenhum está configurado', verbose_name='Tema Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['-is_active', '-is_default', 'name'],
            },
        ),
    ]
