# Generated by Django 5.2.8 on 2025-11-18 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='active_theme',
            field=models.ForeignKey(blank=True, help_text='Selecione o tema visual do site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_active_theme', to='blog.theme', verbose_name='Tema Ativo'),
        ),
    ]
