# Generated by Django 5.2.8 on 2025-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sitesettings_active_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero/Banner'), ('text', 'Texto'), ('text_image', 'Texto com Imagem'), ('image_gallery', 'Galeria de Imagens'), ('cards', 'Cards/Destaques'), ('testimonials', 'Depoimentos'), ('cta', 'Call to Action'), ('features', 'Recursos/Features'), ('banner_carousel', 'Carrossel de Banners'), ('products', 'Produtos'), ('html', 'HTML Customizado')], default='text', max_length=20, verbose_name='Tipo de Seção'),
        ),
    ]
