"""
Django settings for wordpy_cms project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(jwh91h--$h%t$n2o%uxnz8fm-k(8gb5$lw-fx0(4bzm3(e+&r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Interface admin moderna - deve vir antes do admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'taggit',
    'blog',
    'accounts',
    # Dashboard
    'dashboard',
    # Sistema de Módulos
    'modules',
    # Módulos
    'ecommerce',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wordpy_cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'wordpy_cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor Settings
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Silenciar avisos específicos
SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']

# Permitir iframe do CKEditor
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ==============================================================================
# JAZZMIN SETTINGS - Interface Admin Moderna
# ==============================================================================

JAZZMIN_SETTINGS = {
    # Título das páginas
    "site_title": "WordPy CMS Admin",
    "site_header": "WordPy CMS",
    "site_brand": "WordPy",
    "site_logo": None,  # Caminho para o logo
    "login_logo": None,
    "login_logo_dark": None,

    # Logo no topo (texto ou imagem)
    "site_logo_classes": "img-circle",
    "site_icon": None,

    # Texto de boas-vindas na tela de login
    "welcome_sign": "Bem-vindo ao WordPy CMS",

    # Copyright no rodapé
    "copyright": "WordPy CMS - Sistema de Gerenciamento de Conteúdo",

    # Pesquisa no topo
    "search_model": ["auth.User", "blog.Post", "ecommerce.Product"],

    # Nome do usuário no topo
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links no menu superior
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Dashboard", "url": "/admin/dashboard/stats/", "permissions": ["auth.view_user"], "icon": "fas fa-chart-line"},
        {"name": "Configurações", "url": "/admin/blog/sitesettings/", "permissions": ["auth.view_user"], "icon": "fas fa-cogs"},
        {"name": "Suporte", "url": "https://github.com/wordpy/wordpy", "new_window": True},
        {"model": "auth.User"},
    ],

    #############
    # Menu Lateral #
    #############

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Ordenação customizada do menu
    "order_with_respect_to": [
        "auth",
        "modules",
        "blog",
        "ecommerce",
        "messaging",
    ],

    # Ícones customizados para apps e modelos
    "icons": {
        # Apps
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        # Módulos
        "modules": "fas fa-puzzle-piece",
        "modules.Module": "fas fa-cube",
        "modules.ModuleSettings": "fas fa-cog",
        "modules.ModulePermission": "fas fa-key",

        # Blog
        "blog": "fas fa-blog",
        "blog.Post": "fas fa-newspaper",
        "blog.Category": "fas fa-folder",
        "blog.Comment": "fas fa-comments",
        "blog.Page": "fas fa-file-alt",
        "blog.Section": "fas fa-th-large",
        "blog.PageSection": "fas fa-layer-group",
        "blog.SiteSettings": "fas fa-cogs",
        "blog.Theme": "fas fa-palette",
        "blog.Media": "fas fa-images",

        # E-commerce
        "ecommerce": "fas fa-shopping-cart",
        "ecommerce.ProductCategory": "fas fa-tags",
        "ecommerce.Product": "fas fa-box",
        "ecommerce.ProductImage": "fas fa-camera",
        "ecommerce.Cart": "fas fa-shopping-basket",
        "ecommerce.CartItem": "fas fa-cart-plus",
        "ecommerce.Order": "fas fa-receipt",
        "ecommerce.OrderItem": "fas fa-list-ul",

        # Mensagens
        "messaging": "fas fa-envelope",
        "messaging.Conversation": "fas fa-comments",
        "messaging.Message": "fas fa-comment",
        "messaging.MessageReadReceipt": "fas fa-check-double",
        "messaging.BlockedUser": "fas fa-ban",
        "messaging.MessageNotification": "fas fa-bell",

        # Taggit
        "taggit": "fas fa-tag",
        "taggit.Tag": "fas fa-tag",
    },

    # Ícones padrão para ações
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Links relacionados #
    #################

    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############

    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
}

# Configurações de UI do Jazzmin
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",  # default, darkly, solar, etc
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}
